### ISSUE TITLE
Feedback :   phone: event.data.checkout.phone,  this was not available in many store   checkout

### ISSUE THREAD

**Issue by Sky-bits** [lstellway/snippets#1]
@lstellway  Thank you for providing such an excellent code solution for implementing Google Tag Manager (GTM) tracking with Shopify. Your contribution has been valuable.

However, I've encountered a challenge while working with several stores that are on the basic plan on Shopify. Specifically, the basic plan on Shopify does not include the option for users to input their phone number during the checkout process. I believe this limitation could impact the effectiveness of our tracking efforts.

I hope you understand the issue I'm facing and would appreciate any guidance or potential solutions you could provide to address this Shopify basic plan constraint.

Once again, thank you for your exceptional work, and I look forward to your assistance in resolving this matter.

**Comment by lstellway** [comment]
Hi @Sky-bits 

Do you have any more details on your experience? 
_(eg. was there an error thrown in the `console` or anything?)_

I made [an update](https://github.com/lstellway/snippets/commit/1f27f4401236d8bd1173f2856664f2fae9c7ad8f) based on your feedback to more safely reference checkout variables and default to empty strings. 
_(you can just reference [the updated file](https://github.com/lstellway/snippets/blob/1f27f4401236d8bd1173f2856664f2fae9c7ad8f/shopify/google-tag-manager/shopify-pixel.js))_

**Comment by lstellway** [comment]
Closing, but feel free to continue

**Comment by Sky-bits** [comment]
@lstellway  Can This code work with the app pixel ?
